# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# 配置Mapper接口的位置
mybatis:
  type-aliases-package: org.ostenant.springboot.learning.examples.model
  mapper-locations: mapper/*.xml
